### ISSUE TITLE
Does it generate a recombination-free alignment?

### ISSUE THREAD

**Issue by raymondkiu** [kwongj/maskrc-svg#3]
Hello

Just a quick question whether this script generate a recombination-free alignment Fasta? I know it will produce a graph.

Thanks,

Raymond

**Comment by kwongj** [comment]
Yes, the output alignment is in FASTA format with the recombinant sites/columns masked. If you only want the variant sites in this alignment, you can use `snp-sites` (https://github.com/sanger-pathogens/snp-sites) to remove invariant sites.

**Comment by raymondkiu** [comment]
Thanks so much Jason!
